name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
        env:
          JWT_SECRET: $JWT_SECRET
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-dev"

      - name: Deploy to AWS Lambda
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install -n serverless-plugin-for-each && serverless deploy --stage=prd"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
